### ISSUE TITLE
IRC channels appear to be nonfunctional

### ISSUE THREAD

**Issue by corombb** [FuelRats/fuelrats.com#406]
### Describe the bug

Clicking "I Need Fuel" yields an error 502, clicking "I just want to chat" does open an IRC site but trying to connect to #ratchat does not work
![image](https://github.com/user-attachments/assets/c0940b31-d71d-4a8c-aec1-066b01e5d071)

### Expected behavior

I should be able to connect to respective IRC channels

### Steps to reproduce

1. Go to https://fuelrats.com/i-need-fuel
2. click either button

### I can help!

- [ ] I am willing to fix to this issue, and submit it as a PR.

**Comment by UncleClapton** [comment]
Hey @coromd!

Thanks for the report! Good news! Our Inf**rat**structure team were already hard at work resolving the issue and full service was restored yesterday evening.

In the future, please check our [statuspage](https://status.fuelrats.com) before attempting to contact any venue of support. If you suspect a service outage and do not see information there, please contact us at `support@fuelrats.com` instead of opening a ticket on our github repositories. Our github issues should be reserved for site bugs and feature requests, not infrastructure or service issues. Thank you!

**Comment by corombb** [comment]
The status page does not appear to be linked anywhere on the website or any of the GitHub repos, nor is support@fuelrats.com listed on the site anywhere, my apologies
